### PR TITLE
gradle support and usage of Application instead of Activity

### PR DESCRIPTION
**Pull request by k0shk0sh**
Hello there, this pull request improves some stuff such as: 
- code quality and complexity.
- usage of gradle system instead of ant.
- initialize the ACT.init() within the application instead of activity.

### CODE REVIEW

**Comment by macroday** [comment]
Sure Kosh, we will update the system in gradle and activity type.

**Comment by k0shk0sh** [comment]
could i know how certain you are that the POST will be executed before killing the process? i couldn't really get that.

**Comment by macroday** [comment]
First of fall, see the code. I am trigger POST before kill the process. So before dead , the data will be post to you.

**Comment by k0shk0sh** [comment]
that's totally wrong. you cant ensure the user Connectivity. how certain are you that in less than a second that post will be submitted? imo you should make that optional, that's why i attached the jsonobject within the start activity intent whenever i get free time i will do more testing and see what should be done more.

**Comment by macroday** [comment]
Cool kosh,  Yes it will take time to submit the data. So that i processed in asynctask. In my angle, the end user no need to worry about to see the
exception occurred. So that i trigger like this.I will update soon any new methodologies or any
new concept. And thanks gave me suggestion.

**Pull request closed without merging**
